### ISSUE TITLE
cryptomatte doesnt work from fileout put node in blender compositor, in fusion

### ISSUE THREAD

**Issue by adhhrg** [Psyop/Cryptomatte#135]
cryptomatte doesnt work from fileout put node in blender compositor, in fusion

but works in after effect, so I think it can be done in fusion too.

**Comment by EvanAW** [comment]
This isn't an issue with Cryptomatte, but instead it was a long standing issue with Blender's compositor not passing any metadata to the file output node.

This was fixed 3 days ago (Jan 12, 2021) in the 2.92 Beta and 2.93 Alpha builds available at https://builder.blender.org/download/.

See the PR at the following link for more information:
https://developer.blender.org/D10016

**Comment by adhhrg** [comment]
> This isn't an issue with Cryptomatte, but instead it was a long standing issue with Blender's compositor not passing any metadata to the file output node.
> 
> This was fixed 3 days ago (Jan 12, 2021) in the 2.92 Beta and 2.93 Alpha builds available at https://builder.blender.org/download/.
> 
> See the PR at the following link for more information:
> https://developer.blender.org/D10016

just tried it still doesn't work. amm i doing something wrong.
https://developer.blender.org/T64953
the last reply with the video is me

**Comment by EvanAW** [comment]
Just saw your reply now.  

Testing with Blender 2.93.0 Alpha hash: 886486615b35, DaVinci Resolve v17.0.0b.0013, and Cryptomatte 1.2.8, I have no issue using multiple types of ID's in the same Multilayer EXR file.  

Looking into this further, it appears that you are having the same issue as others have reported in https://github.com/Psyop/Cryptomatte/issues/100, that PR https://github.com/Psyop/Cryptomatte/pull/120 is meant to fix.

It is an issue with hash to float conversion in Cryptomatte's Fusion plugin sometimes creating NaN values.

**Comment by cedricduriau** [comment]
Fixed thanks to collaboration with user who created PR #120. Will be shipping in next big release.

Issue: cedricduriau#14
PR: cedricduriau#15
